// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#ifndef PROTOBUF_messages_2eproto__INCLUDED
#define PROTOBUF_messages_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace NetProtocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_messages_2eproto();
void protobuf_AssignDesc_messages_2eproto();
void protobuf_ShutdownFile_messages_2eproto();

class Vector3;
class PlayerRequest;
class PlayerConfirmation;
class PlayerState;
class GameState;
class Error;
class NetPacket;

enum NetPacket_Type {
  NetPacket_Type_VECTOR3 = 1,
  NetPacket_Type_PLAYER_REQUEST = 2,
  NetPacket_Type_PLAYER_CONFIRMATION = 3,
  NetPacket_Type_ERROR = 4
};
bool NetPacket_Type_IsValid(int value);
const NetPacket_Type NetPacket_Type_Type_MIN = NetPacket_Type_VECTOR3;
const NetPacket_Type NetPacket_Type_Type_MAX = NetPacket_Type_ERROR;
const int NetPacket_Type_Type_ARRAYSIZE = NetPacket_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* NetPacket_Type_descriptor();
inline const ::std::string& NetPacket_Type_Name(NetPacket_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    NetPacket_Type_descriptor(), value);
}
inline bool NetPacket_Type_Parse(
    const ::std::string& name, NetPacket_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<NetPacket_Type>(
    NetPacket_Type_descriptor(), name, value);
}
// ===================================================================

class Vector3 : public ::google::protobuf::Message {
 public:
  Vector3();
  virtual ~Vector3();

  Vector3(const Vector3& from);

  inline Vector3& operator=(const Vector3& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector3& default_instance();

  void Swap(Vector3* other);

  // implements Message ----------------------------------------------

  Vector3* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Vector3& from);
  void MergeFrom(const Vector3& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline double x() const;
  inline void set_x(double value);

  // required double y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline double y() const;
  inline void set_y(double value);

  // required double z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline double z() const;
  inline void set_z(double value);

  // @@protoc_insertion_point(class_scope:NetProtocol.Vector3)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  double x_;
  double y_;
  double z_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static Vector3* default_instance_;
};
// -------------------------------------------------------------------

class PlayerRequest : public ::google::protobuf::Message {
 public:
  PlayerRequest();
  virtual ~PlayerRequest();

  PlayerRequest(const PlayerRequest& from);

  inline PlayerRequest& operator=(const PlayerRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerRequest& default_instance();

  void Swap(PlayerRequest* other);

  // implements Message ----------------------------------------------

  PlayerRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerRequest& from);
  void MergeFrom(const PlayerRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:NetProtocol.PlayerRequest)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static PlayerRequest* default_instance_;
};
// -------------------------------------------------------------------

class PlayerConfirmation : public ::google::protobuf::Message {
 public:
  PlayerConfirmation();
  virtual ~PlayerConfirmation();

  PlayerConfirmation(const PlayerConfirmation& from);

  inline PlayerConfirmation& operator=(const PlayerConfirmation& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerConfirmation& default_instance();

  void Swap(PlayerConfirmation* other);

  // implements Message ----------------------------------------------

  PlayerConfirmation* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerConfirmation& from);
  void MergeFrom(const PlayerConfirmation& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:NetProtocol.PlayerConfirmation)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static PlayerConfirmation* default_instance_;
};
// -------------------------------------------------------------------

class PlayerState : public ::google::protobuf::Message {
 public:
  PlayerState();
  virtual ~PlayerState();

  PlayerState(const PlayerState& from);

  inline PlayerState& operator=(const PlayerState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerState& default_instance();

  void Swap(PlayerState* other);

  // implements Message ----------------------------------------------

  PlayerState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerState& from);
  void MergeFrom(const PlayerState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required .NetProtocol.Vector3 position = 2;
  inline bool has_position() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 2;
  inline const ::NetProtocol::Vector3& position() const;
  inline ::NetProtocol::Vector3* mutable_position();
  inline ::NetProtocol::Vector3* release_position();
  inline void set_allocated_position(::NetProtocol::Vector3* position);

  // required uint32 possesion = 3;
  inline bool has_possesion() const;
  inline void clear_possesion();
  static const int kPossesionFieldNumber = 3;
  inline ::google::protobuf::uint32 possesion() const;
  inline void set_possesion(::google::protobuf::uint32 value);

  // required .NetProtocol.Vector3 targetVelocity = 4;
  inline bool has_targetvelocity() const;
  inline void clear_targetvelocity();
  static const int kTargetVelocityFieldNumber = 4;
  inline const ::NetProtocol::Vector3& targetvelocity() const;
  inline ::NetProtocol::Vector3* mutable_targetvelocity();
  inline ::NetProtocol::Vector3* release_targetvelocity();
  inline void set_allocated_targetvelocity(::NetProtocol::Vector3* targetvelocity);

  // required uint32 avatar = 5;
  inline bool has_avatar() const;
  inline void clear_avatar();
  static const int kAvatarFieldNumber = 5;
  inline ::google::protobuf::uint32 avatar() const;
  inline void set_avatar(::google::protobuf::uint32 value);

  // required string name = 6;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 6;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:NetProtocol.PlayerState)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_position();
  inline void clear_has_position();
  inline void set_has_possesion();
  inline void clear_has_possesion();
  inline void set_has_targetvelocity();
  inline void clear_has_targetvelocity();
  inline void set_has_avatar();
  inline void clear_has_avatar();
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::NetProtocol::Vector3* position_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 possesion_;
  ::NetProtocol::Vector3* targetvelocity_;
  ::std::string* name_;
  ::google::protobuf::uint32 avatar_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static PlayerState* default_instance_;
};
// -------------------------------------------------------------------

class GameState : public ::google::protobuf::Message {
 public:
  GameState();
  virtual ~GameState();

  GameState(const GameState& from);

  inline GameState& operator=(const GameState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GameState& default_instance();

  void Swap(GameState* other);

  // implements Message ----------------------------------------------

  GameState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameState& from);
  void MergeFrom(const GameState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .NetProtocol.PlayerState player_state = 1;
  inline int player_state_size() const;
  inline void clear_player_state();
  static const int kPlayerStateFieldNumber = 1;
  inline const ::NetProtocol::PlayerState& player_state(int index) const;
  inline ::NetProtocol::PlayerState* mutable_player_state(int index);
  inline ::NetProtocol::PlayerState* add_player_state();
  inline const ::google::protobuf::RepeatedPtrField< ::NetProtocol::PlayerState >&
      player_state() const;
  inline ::google::protobuf::RepeatedPtrField< ::NetProtocol::PlayerState >*
      mutable_player_state();

  // @@protoc_insertion_point(class_scope:NetProtocol.GameState)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::NetProtocol::PlayerState > player_state_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static GameState* default_instance_;
};
// -------------------------------------------------------------------

class Error : public ::google::protobuf::Message {
 public:
  Error();
  virtual ~Error();

  Error(const Error& from);

  inline Error& operator=(const Error& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Error& default_instance();

  void Swap(Error* other);

  // implements Message ----------------------------------------------

  Error* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Error& from);
  void MergeFrom(const Error& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 errorCode = 1;
  inline bool has_errorcode() const;
  inline void clear_errorcode();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::uint32 errorcode() const;
  inline void set_errorcode(::google::protobuf::uint32 value);

  // required string errorMsg = 2;
  inline bool has_errormsg() const;
  inline void clear_errormsg();
  static const int kErrorMsgFieldNumber = 2;
  inline const ::std::string& errormsg() const;
  inline void set_errormsg(const ::std::string& value);
  inline void set_errormsg(const char* value);
  inline void set_errormsg(const char* value, size_t size);
  inline ::std::string* mutable_errormsg();
  inline ::std::string* release_errormsg();
  inline void set_allocated_errormsg(::std::string* errormsg);

  // @@protoc_insertion_point(class_scope:NetProtocol.Error)
 private:
  inline void set_has_errorcode();
  inline void clear_has_errorcode();
  inline void set_has_errormsg();
  inline void clear_has_errormsg();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* errormsg_;
  ::google::protobuf::uint32 errorcode_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static Error* default_instance_;
};
// -------------------------------------------------------------------

class NetPacket : public ::google::protobuf::Message {
 public:
  NetPacket();
  virtual ~NetPacket();

  NetPacket(const NetPacket& from);

  inline NetPacket& operator=(const NetPacket& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NetPacket& default_instance();

  void Swap(NetPacket* other);

  // implements Message ----------------------------------------------

  NetPacket* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NetPacket& from);
  void MergeFrom(const NetPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef NetPacket_Type Type;
  static const Type VECTOR3 = NetPacket_Type_VECTOR3;
  static const Type PLAYER_REQUEST = NetPacket_Type_PLAYER_REQUEST;
  static const Type PLAYER_CONFIRMATION = NetPacket_Type_PLAYER_CONFIRMATION;
  static const Type ERROR = NetPacket_Type_ERROR;
  static inline bool Type_IsValid(int value) {
    return NetPacket_Type_IsValid(value);
  }
  static const Type Type_MIN =
    NetPacket_Type_Type_MIN;
  static const Type Type_MAX =
    NetPacket_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    NetPacket_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return NetPacket_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return NetPacket_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return NetPacket_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .NetProtocol.NetPacket.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::NetProtocol::NetPacket_Type type() const;
  inline void set_type(::NetProtocol::NetPacket_Type value);

  // optional .NetProtocol.Vector3 vector3 = 2;
  inline bool has_vector3() const;
  inline void clear_vector3();
  static const int kVector3FieldNumber = 2;
  inline const ::NetProtocol::Vector3& vector3() const;
  inline ::NetProtocol::Vector3* mutable_vector3();
  inline ::NetProtocol::Vector3* release_vector3();
  inline void set_allocated_vector3(::NetProtocol::Vector3* vector3);

  // optional .NetProtocol.PlayerRequest player_request = 3;
  inline bool has_player_request() const;
  inline void clear_player_request();
  static const int kPlayerRequestFieldNumber = 3;
  inline const ::NetProtocol::PlayerRequest& player_request() const;
  inline ::NetProtocol::PlayerRequest* mutable_player_request();
  inline ::NetProtocol::PlayerRequest* release_player_request();
  inline void set_allocated_player_request(::NetProtocol::PlayerRequest* player_request);

  // optional .NetProtocol.PlayerConfirmation player_confirmation = 4;
  inline bool has_player_confirmation() const;
  inline void clear_player_confirmation();
  static const int kPlayerConfirmationFieldNumber = 4;
  inline const ::NetProtocol::PlayerConfirmation& player_confirmation() const;
  inline ::NetProtocol::PlayerConfirmation* mutable_player_confirmation();
  inline ::NetProtocol::PlayerConfirmation* release_player_confirmation();
  inline void set_allocated_player_confirmation(::NetProtocol::PlayerConfirmation* player_confirmation);

  // optional .NetProtocol.Error error = 5;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 5;
  inline const ::NetProtocol::Error& error() const;
  inline ::NetProtocol::Error* mutable_error();
  inline ::NetProtocol::Error* release_error();
  inline void set_allocated_error(::NetProtocol::Error* error);

  // @@protoc_insertion_point(class_scope:NetProtocol.NetPacket)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_vector3();
  inline void clear_has_vector3();
  inline void set_has_player_request();
  inline void clear_has_player_request();
  inline void set_has_player_confirmation();
  inline void clear_has_player_confirmation();
  inline void set_has_error();
  inline void clear_has_error();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::NetProtocol::Vector3* vector3_;
  ::NetProtocol::PlayerRequest* player_request_;
  ::NetProtocol::PlayerConfirmation* player_confirmation_;
  ::NetProtocol::Error* error_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_messages_2eproto();
  friend void protobuf_AssignDesc_messages_2eproto();
  friend void protobuf_ShutdownFile_messages_2eproto();

  void InitAsDefaultInstance();
  static NetPacket* default_instance_;
};
// ===================================================================


// ===================================================================

// Vector3

// required double x = 1;
inline bool Vector3::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vector3::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vector3::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vector3::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Vector3::x() const {
  return x_;
}
inline void Vector3::set_x(double value) {
  set_has_x();
  x_ = value;
}

// required double y = 2;
inline bool Vector3::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vector3::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vector3::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vector3::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Vector3::y() const {
  return y_;
}
inline void Vector3::set_y(double value) {
  set_has_y();
  y_ = value;
}

// required double z = 3;
inline bool Vector3::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Vector3::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Vector3::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Vector3::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Vector3::z() const {
  return z_;
}
inline void Vector3::set_z(double value) {
  set_has_z();
  z_ = value;
}

// -------------------------------------------------------------------

// PlayerRequest

// required string name = 1;
inline bool PlayerRequest::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerRequest::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerRequest::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerRequest::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& PlayerRequest::name() const {
  return *name_;
}
inline void PlayerRequest::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void PlayerRequest::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void PlayerRequest::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PlayerRequest::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* PlayerRequest::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PlayerRequest::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// PlayerConfirmation

// required uint32 id = 1;
inline bool PlayerConfirmation::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerConfirmation::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerConfirmation::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerConfirmation::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 PlayerConfirmation::id() const {
  return id_;
}
inline void PlayerConfirmation::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// PlayerState

// required uint32 id = 1;
inline bool PlayerState::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerState::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerState::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerState::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 PlayerState::id() const {
  return id_;
}
inline void PlayerState::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required .NetProtocol.Vector3 position = 2;
inline bool PlayerState::has_position() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PlayerState::set_has_position() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PlayerState::clear_has_position() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PlayerState::clear_position() {
  if (position_ != NULL) position_->::NetProtocol::Vector3::Clear();
  clear_has_position();
}
inline const ::NetProtocol::Vector3& PlayerState::position() const {
  return position_ != NULL ? *position_ : *default_instance_->position_;
}
inline ::NetProtocol::Vector3* PlayerState::mutable_position() {
  set_has_position();
  if (position_ == NULL) position_ = new ::NetProtocol::Vector3;
  return position_;
}
inline ::NetProtocol::Vector3* PlayerState::release_position() {
  clear_has_position();
  ::NetProtocol::Vector3* temp = position_;
  position_ = NULL;
  return temp;
}
inline void PlayerState::set_allocated_position(::NetProtocol::Vector3* position) {
  delete position_;
  position_ = position;
  if (position) {
    set_has_position();
  } else {
    clear_has_position();
  }
}

// required uint32 possesion = 3;
inline bool PlayerState::has_possesion() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PlayerState::set_has_possesion() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PlayerState::clear_has_possesion() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PlayerState::clear_possesion() {
  possesion_ = 0u;
  clear_has_possesion();
}
inline ::google::protobuf::uint32 PlayerState::possesion() const {
  return possesion_;
}
inline void PlayerState::set_possesion(::google::protobuf::uint32 value) {
  set_has_possesion();
  possesion_ = value;
}

// required .NetProtocol.Vector3 targetVelocity = 4;
inline bool PlayerState::has_targetvelocity() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PlayerState::set_has_targetvelocity() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PlayerState::clear_has_targetvelocity() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PlayerState::clear_targetvelocity() {
  if (targetvelocity_ != NULL) targetvelocity_->::NetProtocol::Vector3::Clear();
  clear_has_targetvelocity();
}
inline const ::NetProtocol::Vector3& PlayerState::targetvelocity() const {
  return targetvelocity_ != NULL ? *targetvelocity_ : *default_instance_->targetvelocity_;
}
inline ::NetProtocol::Vector3* PlayerState::mutable_targetvelocity() {
  set_has_targetvelocity();
  if (targetvelocity_ == NULL) targetvelocity_ = new ::NetProtocol::Vector3;
  return targetvelocity_;
}
inline ::NetProtocol::Vector3* PlayerState::release_targetvelocity() {
  clear_has_targetvelocity();
  ::NetProtocol::Vector3* temp = targetvelocity_;
  targetvelocity_ = NULL;
  return temp;
}
inline void PlayerState::set_allocated_targetvelocity(::NetProtocol::Vector3* targetvelocity) {
  delete targetvelocity_;
  targetvelocity_ = targetvelocity;
  if (targetvelocity) {
    set_has_targetvelocity();
  } else {
    clear_has_targetvelocity();
  }
}

// required uint32 avatar = 5;
inline bool PlayerState::has_avatar() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PlayerState::set_has_avatar() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PlayerState::clear_has_avatar() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PlayerState::clear_avatar() {
  avatar_ = 0u;
  clear_has_avatar();
}
inline ::google::protobuf::uint32 PlayerState::avatar() const {
  return avatar_;
}
inline void PlayerState::set_avatar(::google::protobuf::uint32 value) {
  set_has_avatar();
  avatar_ = value;
}

// required string name = 6;
inline bool PlayerState::has_name() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PlayerState::set_has_name() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PlayerState::clear_has_name() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PlayerState::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& PlayerState::name() const {
  return *name_;
}
inline void PlayerState::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void PlayerState::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void PlayerState::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PlayerState::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* PlayerState::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PlayerState::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// GameState

// repeated .NetProtocol.PlayerState player_state = 1;
inline int GameState::player_state_size() const {
  return player_state_.size();
}
inline void GameState::clear_player_state() {
  player_state_.Clear();
}
inline const ::NetProtocol::PlayerState& GameState::player_state(int index) const {
  return player_state_.Get(index);
}
inline ::NetProtocol::PlayerState* GameState::mutable_player_state(int index) {
  return player_state_.Mutable(index);
}
inline ::NetProtocol::PlayerState* GameState::add_player_state() {
  return player_state_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::NetProtocol::PlayerState >&
GameState::player_state() const {
  return player_state_;
}
inline ::google::protobuf::RepeatedPtrField< ::NetProtocol::PlayerState >*
GameState::mutable_player_state() {
  return &player_state_;
}

// -------------------------------------------------------------------

// Error

// required uint32 errorCode = 1;
inline bool Error::has_errorcode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Error::set_has_errorcode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Error::clear_has_errorcode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Error::clear_errorcode() {
  errorcode_ = 0u;
  clear_has_errorcode();
}
inline ::google::protobuf::uint32 Error::errorcode() const {
  return errorcode_;
}
inline void Error::set_errorcode(::google::protobuf::uint32 value) {
  set_has_errorcode();
  errorcode_ = value;
}

// required string errorMsg = 2;
inline bool Error::has_errormsg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Error::set_has_errormsg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Error::clear_has_errormsg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Error::clear_errormsg() {
  if (errormsg_ != &::google::protobuf::internal::kEmptyString) {
    errormsg_->clear();
  }
  clear_has_errormsg();
}
inline const ::std::string& Error::errormsg() const {
  return *errormsg_;
}
inline void Error::set_errormsg(const ::std::string& value) {
  set_has_errormsg();
  if (errormsg_ == &::google::protobuf::internal::kEmptyString) {
    errormsg_ = new ::std::string;
  }
  errormsg_->assign(value);
}
inline void Error::set_errormsg(const char* value) {
  set_has_errormsg();
  if (errormsg_ == &::google::protobuf::internal::kEmptyString) {
    errormsg_ = new ::std::string;
  }
  errormsg_->assign(value);
}
inline void Error::set_errormsg(const char* value, size_t size) {
  set_has_errormsg();
  if (errormsg_ == &::google::protobuf::internal::kEmptyString) {
    errormsg_ = new ::std::string;
  }
  errormsg_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Error::mutable_errormsg() {
  set_has_errormsg();
  if (errormsg_ == &::google::protobuf::internal::kEmptyString) {
    errormsg_ = new ::std::string;
  }
  return errormsg_;
}
inline ::std::string* Error::release_errormsg() {
  clear_has_errormsg();
  if (errormsg_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = errormsg_;
    errormsg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Error::set_allocated_errormsg(::std::string* errormsg) {
  if (errormsg_ != &::google::protobuf::internal::kEmptyString) {
    delete errormsg_;
  }
  if (errormsg) {
    set_has_errormsg();
    errormsg_ = errormsg;
  } else {
    clear_has_errormsg();
    errormsg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// NetPacket

// required .NetProtocol.NetPacket.Type type = 1;
inline bool NetPacket::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NetPacket::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NetPacket::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NetPacket::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::NetProtocol::NetPacket_Type NetPacket::type() const {
  return static_cast< ::NetProtocol::NetPacket_Type >(type_);
}
inline void NetPacket::set_type(::NetProtocol::NetPacket_Type value) {
  assert(::NetProtocol::NetPacket_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional .NetProtocol.Vector3 vector3 = 2;
inline bool NetPacket::has_vector3() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NetPacket::set_has_vector3() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NetPacket::clear_has_vector3() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NetPacket::clear_vector3() {
  if (vector3_ != NULL) vector3_->::NetProtocol::Vector3::Clear();
  clear_has_vector3();
}
inline const ::NetProtocol::Vector3& NetPacket::vector3() const {
  return vector3_ != NULL ? *vector3_ : *default_instance_->vector3_;
}
inline ::NetProtocol::Vector3* NetPacket::mutable_vector3() {
  set_has_vector3();
  if (vector3_ == NULL) vector3_ = new ::NetProtocol::Vector3;
  return vector3_;
}
inline ::NetProtocol::Vector3* NetPacket::release_vector3() {
  clear_has_vector3();
  ::NetProtocol::Vector3* temp = vector3_;
  vector3_ = NULL;
  return temp;
}
inline void NetPacket::set_allocated_vector3(::NetProtocol::Vector3* vector3) {
  delete vector3_;
  vector3_ = vector3;
  if (vector3) {
    set_has_vector3();
  } else {
    clear_has_vector3();
  }
}

// optional .NetProtocol.PlayerRequest player_request = 3;
inline bool NetPacket::has_player_request() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NetPacket::set_has_player_request() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NetPacket::clear_has_player_request() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NetPacket::clear_player_request() {
  if (player_request_ != NULL) player_request_->::NetProtocol::PlayerRequest::Clear();
  clear_has_player_request();
}
inline const ::NetProtocol::PlayerRequest& NetPacket::player_request() const {
  return player_request_ != NULL ? *player_request_ : *default_instance_->player_request_;
}
inline ::NetProtocol::PlayerRequest* NetPacket::mutable_player_request() {
  set_has_player_request();
  if (player_request_ == NULL) player_request_ = new ::NetProtocol::PlayerRequest;
  return player_request_;
}
inline ::NetProtocol::PlayerRequest* NetPacket::release_player_request() {
  clear_has_player_request();
  ::NetProtocol::PlayerRequest* temp = player_request_;
  player_request_ = NULL;
  return temp;
}
inline void NetPacket::set_allocated_player_request(::NetProtocol::PlayerRequest* player_request) {
  delete player_request_;
  player_request_ = player_request;
  if (player_request) {
    set_has_player_request();
  } else {
    clear_has_player_request();
  }
}

// optional .NetProtocol.PlayerConfirmation player_confirmation = 4;
inline bool NetPacket::has_player_confirmation() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NetPacket::set_has_player_confirmation() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NetPacket::clear_has_player_confirmation() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NetPacket::clear_player_confirmation() {
  if (player_confirmation_ != NULL) player_confirmation_->::NetProtocol::PlayerConfirmation::Clear();
  clear_has_player_confirmation();
}
inline const ::NetProtocol::PlayerConfirmation& NetPacket::player_confirmation() const {
  return player_confirmation_ != NULL ? *player_confirmation_ : *default_instance_->player_confirmation_;
}
inline ::NetProtocol::PlayerConfirmation* NetPacket::mutable_player_confirmation() {
  set_has_player_confirmation();
  if (player_confirmation_ == NULL) player_confirmation_ = new ::NetProtocol::PlayerConfirmation;
  return player_confirmation_;
}
inline ::NetProtocol::PlayerConfirmation* NetPacket::release_player_confirmation() {
  clear_has_player_confirmation();
  ::NetProtocol::PlayerConfirmation* temp = player_confirmation_;
  player_confirmation_ = NULL;
  return temp;
}
inline void NetPacket::set_allocated_player_confirmation(::NetProtocol::PlayerConfirmation* player_confirmation) {
  delete player_confirmation_;
  player_confirmation_ = player_confirmation;
  if (player_confirmation) {
    set_has_player_confirmation();
  } else {
    clear_has_player_confirmation();
  }
}

// optional .NetProtocol.Error error = 5;
inline bool NetPacket::has_error() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void NetPacket::set_has_error() {
  _has_bits_[0] |= 0x00000010u;
}
inline void NetPacket::clear_has_error() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void NetPacket::clear_error() {
  if (error_ != NULL) error_->::NetProtocol::Error::Clear();
  clear_has_error();
}
inline const ::NetProtocol::Error& NetPacket::error() const {
  return error_ != NULL ? *error_ : *default_instance_->error_;
}
inline ::NetProtocol::Error* NetPacket::mutable_error() {
  set_has_error();
  if (error_ == NULL) error_ = new ::NetProtocol::Error;
  return error_;
}
inline ::NetProtocol::Error* NetPacket::release_error() {
  clear_has_error();
  ::NetProtocol::Error* temp = error_;
  error_ = NULL;
  return temp;
}
inline void NetPacket::set_allocated_error(::NetProtocol::Error* error) {
  delete error_;
  error_ = error;
  if (error) {
    set_has_error();
  } else {
    clear_has_error();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace NetProtocol

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::NetProtocol::NetPacket_Type>() {
  return ::NetProtocol::NetPacket_Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messages_2eproto__INCLUDED
